name: Release Docker

on:
  push:
    branches:
      - "main"
  release:
    types: [published]

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY  || 'quay.io' }}
  GUIAGENT_NAME: ${{ vars.GUIAGENT_NAME || 'luweb/screenpipe' }}
  GUIAGENT_CLI_NAME: ${{ vars.GUIAGENT_CLI_NAME || 'luweb/screenpipe-cli' }}
  GUIAGENT_APP_NAME: ${{ vars.GUIAGENT_APP_NAME || 'luweb/screenpipe-app' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # - name: Checkout
      #   uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry ${{ env.DOCKER_REGISTRY }}
        # uses: docker/login-action@v2
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Prepare Custom Scripts
        run: |
            pwd
            ls -l 
      #       cd ./web/
      #       bash -x ./custom.sh

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          # build-args: COMMIT_SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.GUIAGENT_NAME }}-all:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
